"use client";

import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import connectMongoDB from "@/lib/mongodb";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
const queryClient = new QueryClient();

const poppins = Poppins({ subsets: ["latin"], weight: ["400", "700"] });

// export const metadata: Metadata = {
//     title: "Cut Here",
//     description: "Generated by create next app",
// };

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    // const response: any = await connectMongoDB();
    // console.log(response)

    // if (response === false) {
    //     return (
    //         <div className="container mx-auto flex items-center justify-center">
    //             <div>
    //               <p>hello</p>
    //             </div>
    //         </div>
    //     );
    // }
    return (
        <QueryClientProvider client={queryClient}>
            <html lang="en">
                <body className={poppins.className}>{children}</body>
            </html>
        </QueryClientProvider>
    );
}
